services:
  postgres:
    container_name: postgres_container
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: api_database
    volumes:
      - postgres:/data/postgres
    ports:
      - "5432:5432"
    networks:
      - workordernetwork

  api1:
    container_name: api_container1
    build:
      context: API
      dockerfile: Dockerfile
    command: >
      sh -c ' mvn clean install && java -jar target/api-1.0.jar'
    environment:
      API_PORT: 8080
      DATABASE_URL: jdbc:postgresql://postgres:5432/api_database
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8080:8080"
    depends_on:
      postgres:
        condition: service_started
    networks:
      - workordernetwork

  api2:
    container_name: api_container2
    build:
      context: API
      dockerfile: Dockerfile
    command: >
      sh -c ' mvn clean install && java -jar target/api-1.0.jar'
    environment:
      API_PORT: 8081
      DATABASE_URL: jdbc:postgresql://postgres:5432/api_database
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: postgres
    ports:
      - "8081:8081"
    depends_on:
      postgres:
        condition: service_started
    networks:
      - workordernetwork

  nginx:
    container_name: nginx_container
    image: nginx:latest
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d
    ports:
      - 80:80
    depends_on:
      - api1
      - api2
    networks:
      - workordernetwork

volumes:
  postgres:


networks:
  workordernetwork:
